services:
  - type: web
    name: wilderness-frontend-dev
    runtime: docker
    branch: main
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    rootDirectory: ./frontend
    port: 80  # Changed from 3000
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://localhost:4000
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    numInstances: 1